<a href="https://colab.research.google.com/github/shaniaakhan21/Disease_Prediction_System/blob/main/Copy_of_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Creating an array in NumPy**


In [ ]:
#using np as alias for numpy
import numpy as np

#creating ndarray object using .array() 
arr = np.array([1, 2, 3, 4, 5])

#printing ndarray
print(arr)

#type of the object 'arr'
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


#2-D arrays with Numpy

In [ ]:
import numpy as np
 #creating a 2-D array
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

#accessing the 4th element in the first dimension
print(arr[0, 3]) 

4


#3-D arrays




In [ ]:
import numpy as np
#creating a 3-D array
arr = np.array([[[1, 2, 3], [4, 5, 6], [16, 17, 18]], [[7, 8, 9], [10, 11, 12], [13, 14, 15]]])

#accessing the 1st element in the third array of the second array
print(arr[1, 2, 0]) 

13


#Negative Indexing

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print('last second element: ', arr1[-2])

arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr2[1, -1]) 

last second element:  4
Last element from 2nd dim:  10


# **#Array Slicing**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
#Slice elements from index 4 to the end of the array:
print(arr[4:]) 

#Slice elements from index 1 to index 5 from the following array:
print(arr[1:5]) 

#Slice elements from the beginning to index 4 (not included):
print(arr[:4])

#Negative Slicing: Slice from the index 3 from the end to index 1 from the end:
print(arr[-3:-1]) 

#Return every other element from index 1 to index 5: "STEP"
print(arr[1:5:2]) 

[5 6 7]
[2 3 4 5]
[1 2 3 4]
[5 6]
[2 4]


#Slicing 2-D arrays

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

#From the second element, slice elements from index 1 to index 4 (not included):
print(arr[1, 1:4]) 

#From both elements, return index 2:
print(arr[0:2, 2])

#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(arr[0:2, 1:4] )

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


#**Checking the data type of an array:**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr.dtype) 

#string data type
sarr = np.array(['apple', 'banana', 'cherry'])
print(sarr.dtype) 

int64
<U6


#**Creating Arrays With a Defined Data Type**

In [ ]:
import numpy as np
#creating an array with data type string
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype) 
#creating an array with data type 4-byte integer
iarr = np.array([1, 2, 3, 4], dtype='i4')

print(iarr)
print(iarr.dtype) 

[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32


#Coverting String into Float using Numpy

In [ ]:
# Process utilizing astype() function

# Import NumPy Library
import numpy as np

# Initialize our Array with Strings
# The String Type is denoted by the quotes ""
initialArray = ["1.1", "2.2", "3.3", "4.4"]

# Convert initial Array to NumPy Array
# Use the array() function
sampleArray = np.array(initialArray)

# Print our Initial Array
print("Our initial array: ", initialArray)
print("Original type: " , type(initialArray[0]))

# Actual Conversion of Array
# Note usage of astype() function
# np.float can be changed to represent differing types
convertedArray = sampleArray.astype(np.float)

# Print our final result
# Note that usage of str() is due to Python conventions
print("Our final array: ", convertedArray)
print("Final type: " , type(convertedArray[0]))


Our initial array:  ['1.1', '2.2', '3.3', '4.4']
Original type:  <class 'str'>
Our final array:  [1.1 2.2 3.3 4.4]
Final type:  <class 'numpy.float64'>


#Coverting Float into integers using Numpy

In [ ]:
A = np.array((0.4, 1.6, 2.1, -3.7, 2.9))
print(A)

A = A.astype(int)
print(A)
print(type(A[1]))



[ 0.4  1.6  2.1 -3.7  2.9]
[ 0  1  2 -3  2]
<class 'numpy.int64'>


#Coverting integers into Float using Numpy

In [ ]:
A = np.array((0, 1, 2, -3, 2))
print(A)
print(type(A[0]))

A = A.astype(float)
print(A)
print(type(A[1]))

[ 0  1  2 -3  2]
<class 'numpy.int64'>
[ 0.  1.  2. -3.  2.]
<class 'numpy.float64'>


#Reading a CSV File in Python
~Using numpy , genfromtxt() function

In [8]:
import numpy as np
data = np.genfromtxt('company_sales_data.csv', dtype= None, delimiter=',',skip_header=1)
print(data)

[[     1   2500   1500   5200   9200   1200   1500  21100 211000]
 [     2   2630   1200   5100   6100   2100   1200  18330 183300]
 [     3   2140   1340   4550   9550   3550   1340  22470 224700]
 [     4   3400   1130   5870   8870   1870   1130  22270 222700]
 [     5   3600   1740   4560   7760   1560   1740  20960 209600]
 [     6   2760   1555   4890   7490   1890   1555  20140 201400]
 [     7   2980   1120   4780   8980   1780   1120  29550 295500]
 [     8   3700   1400   5860   9960   2860   1400  36140 361400]
 [     9   3540   1780   6100   8100   2100   1780  23400 234000]
 [    10   1990   1890   8300  10300   2300   1890  26670 266700]
 [    11   2340   2100   7300  13300   2400   2100  41280 412800]
 [    12   2900   1760   7400  14400   1800   1760  30020 300200]]
